### ISSUE TITLE
Unable to load homepage editor

### ISSUE THREAD

**Issue by statsturtle** [EduardoKrausME/moodle-theme_degrade#15]
I'm unable to load the home page editor: 

<img width="662" alt="homepage_editor1" src="https://github.com/user-attachments/assets/2698b58a-8d39-40d1-b907-844fab87b217">

I'm just stuck with the loading icon: 

<img width="1041" alt="homepage_editor2" src="https://github.com/user-attachments/assets/49c73357-89b3-4f87-bf23-66edb9d62227">

On another Moodle site, I am using a previous version of the Degrade plugin and am able to access the editor without problems.

**Comment by gajuro** [comment]
Same here.

**Comment by eduardokraus** [comment]
Take a test now

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-theme_degrade/commit/39f2aeeb6c69f9a578c5d982902bc3997e18f17e
