### ISSUE TITLE
Tema Moodle Degradê deixando tudo no modo escuro.

### ISSUE THREAD

**Issue by Destruidoss** [EduardoKrausME/moodle-theme_degrade#18]
![image](https://github.com/user-attachments/assets/60baecfe-278e-42db-956e-0eae83caadfe)

após atualizar o tema ele permanece somente escuro, não encontro opção para voltar para o claro, selecionando o light Mode nada acontece.

**Comment by eduardokraus** [comment]
Subi atualização corrigindo a pouco

**Comment by Destruidoss** [comment]
Obrigado, corrigido.
