### ISSUE TITLE
Impossible to use this plugin with my Moodle 4.1 in administration mode

### ISSUE THREAD

**Issue by gigadep** [EduardoKrausME/moodle-theme_degrade#7]
I tried to install this theme with my Moodle 4.1 but when I use my admin account, I have the message "ERR_TOO_MANY_REDIRECTS" on the page Administration>General>Notification.

**Comment by eduardokraus** [comment]
![Captura de Tela 2023-04-06 às 19 00 40](https://user-images.githubusercontent.com/7725236/230501935-9edc4cb5-6fdf-4d1e-8bd0-45e184976853.png)
![Captura de Tela 2023-04-06 às 19 00 54](https://user-images.githubusercontent.com/7725236/230501956-43f48baa-1862-4f5e-bc57-4b10bb3602fc.png)
