### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by groiso** [EduardoKrausME/moodle-theme_degrade#9]
Hi,
I would like to customize the footer with HTML, to accompany another Wordpress theme.

In which directory can I find the code to make this change?

If I make a change, will I lose everything in the update? Is there any way not to lose?

Thanks

**Comment by eduardokraus** [comment]
Hello groiso,

What a great idea you've given me! Customizing the footer with HTML to match another theme of the site is indeed a way to add a special touch to your Moodle. Let's get started!

You can do this by accessing the theme settings. Within these settings, look for the footer option and change it to "Page to be created with editor." Once you've done that, you'll have access to an editor that will allow you to edit the HTML of the footer directly, without needing to mess with the theme files.

This way, your customizations will be safe and won't be lost during Moodle updates.

**Comment by eduardokraus** [comment]
Hello groiso,

What a great idea you've given me! Customizing the footer with HTML to match another theme of the site is indeed a way to add a special touch to your Moodle. Let's get started!

You can do this by accessing the theme settings. Within these settings, look for the footer option and change it to "Page to be created with editor." Once you've done that, you'll have access to an editor that will allow you to edit the HTML of the footer directly, without needing to mess with the theme files.

This way, your customizations will be safe and won't be lost during Moodle updates.
